### ISSUE TITLE
Additional profile configurations

### ISSUE THREAD

**Issue by ericlaw1979** [WPO-Foundation/win-shaper#3]
Is there a good source of data for other possible configurations that users might want to add? 

The two that immediately come to mind are:

   - Satellite (the numbers I saw were 1mb/256k, 3% loss, 638ms RTT)
   - Australia to US

...but I'm sure that different users will be interested in different numbers, and eventually there will probably be overlapping sets of people who have very specific needs. Rather than embedding them all into the tool itself, maybe put a wiki page up on this GitHub site?

**Comment by pmeenan** [comment]
I'd be happy to host a page where people could contribute profiles (just a text markdown page) with the requirement that the data souces be attributed or the measurement methodology be documented.

There aren't good public sources that I'm aware of and even some of the private sources have issues that need to be considered.

Facebook has a [few profiles](https://github.com/facebook/augmented-traffic-control/tree/master/utils/profiles) as part of ATC but I'm not sure what the underlying souce of the data is.

Early-on I used the FTC broadband reports which included both bandwidth and latency data (latency is always the harder one to get a source for).  Not sure if they still include latency data but they are very US focused and I'm not sure if they include Satellite.  The satellite numbers look reasonable but I have seen lots of satellite plans with higher downlink speeds than that and they tend to have their own built-in retransmissions at L2 so packet loss may not be accurate (and sometimes it is hard to tell if packet loss is real or because of long-delayed ACKs).

Open Signal has a pretty good set of data for mobile connections but like most data sources, they don't show you the distributions and percentiles.

Probably the best data source I've seen is Ookla's speed test data but it isn't public and it is skewed by people who run the speed tests.

RTT data from the field (measured on the server, from resource/navigation timing or Chrome's UMA) has an interesting problem with bufferbloat, particularly on lower-end mobile connections.  If there is any other network activity going on the RTTs can look longer than they really are at the physical level because of buffering and you want to make sure you model the physical RTT (since the buffering will happen automatically).  Usually that means looking at the initial RTT for the connection for the base page and hoping there isn't other traffic in flight.

As far as Australia <-> US goes, I don't usually recommend trying to model geographic distribution because it is incredibly hard to do right.  If you know for sure that all of the content is served from a single origin then adding the long-haul latency to the connection should be fine but at least for websites that is usually not the case.  As soon as third-party content and CDN's come into play the modeling gets very messy.  In the Australia case in particular there is a huge difference if something can be served from an in-country CDN.
