### ISSUE TITLE
windows 7 target?

### ISSUE THREAD

**Issue by takigama** [WPO-Foundation/win-shaper#8]
Windows dev is not my forte by any stretch, but I was trying to figure out what might be required to compile for windows 7 and wasnt able to get very far with it. Is there anything missing in win 7 that wouldn't work with win-shaper before I persist with it a little while longer?

**Comment by pmeenan** [comment]
Unfortunately windows 7 doesn't support the [layer-2 WFP intercepts](https://msdn.microsoft.com/en-us/windows/hardware/drivers/network/using-layer-2-filtering) that winshaper needs (otherwise I absolutely would have done it because it would make my life a lot easier).

It might be possible to fall-back to intercepting at a higher level but filtering at L2 for traffic-shaping is much cleaner and easier to model real world.

**Comment by takigama** [comment]
Yes, i kinda figured it would be something along those lines. Did have a play with trying to find a way of doing this in win 7, but that is well beyond my capabilities i think. Had a look at the implementations of other switches in win 7 (such as virtualbox's) but really didnt get very far. Still, all good, thanks for the reply!
